const EMPLOYEE_REQUIRED_FIELD_LABELS: Record<string, string> = {
    employee_no: 'Employee number',
    name: 'Name',
    image: 'Photo',
    branch_id: 'Branch',
    department_id: 'Department',
    position_id: 'Position',
    rank_id: 'Rank',
    project_id: 'Project name',
    client_id: 'Client',
    date_of_birth: 'Date of birth',
    hire_date: 'Date of hire',
    place_of_birth: 'Place of birth',
    gender_id: 'Gender',
    religion_id: 'Religion',
    visa_type_id: 'Visa type',
    company_visa_type_id: 'Sponsor',
    approval_location_ids: 'Approval locations',
    sssa_option_ids: 'SSSA options',
    nationality_id: 'Nationality',
    marital_status: 'Marital status',
    spouse_name: 'Spouse name',
    personal_email: 'Personal email',
    work_email: 'Work email',
    phone: 'Phone',
    phone_home_country: 'Home country phone',
    nearest_airport: 'Nearest airport',
    emergency_contact: 'Emergency contact',
    emergency_phone: 'Emergency phone',
    address: 'Address',
    emirates_id: 'Emirates ID',
    passport_number: 'Passport number',
    status: 'Status',
    crew_status: 'Crew status',
    payroll_category: 'Payroll category',
    start_date: 'Start date',
    end_date: 'End date',
    labor_contract_id: 'Labor contract ID',
    basic_salary: 'Basic salary',
    housing_allowance: 'Housing allowance',
    transport_allowance: 'Transport allowance',
    other_allowances: 'Other allowances',
    supplementary_allowance: 'Supplementary allowance',
    site_allowance: 'Site allowance',
    note: 'Note',
    bank_id: 'Bank',
    iban: 'IBAN',
    account_name: 'Account name',
    is_primary: 'Primary account',
    certificate: 'Certificate',
    university: 'University',
    country_id: 'Country',
    company_name: 'Company name',
    job_title: 'Job title',
    date_from: 'Start date',
    date_to: 'End date',
    responsibility: 'Responsibility',
    language_name: 'Language',
    is_spoken: 'Spoken',
    is_written: 'Written',
    is_understood: 'Understood',
    is_mother_tongue: 'Mother tongue',
    course_id: 'Course',
    expiry_date: 'Expiry date',
    institute_center: 'Institute / center',
    certificate_path: 'Certificate file',
    vessel_type_id: 'Vessel type',
    vessel_id: 'Vessel',
    client_id: 'Client',
    is_offshore: 'Offshore',
    document_type_id: 'Document type',
    title: 'Title',
    document_number: 'Document number',
    notes: 'Notes',
    vaccination_name: 'Vaccination name',
    first_dose_date: 'First dose date',
    second_dose_date: 'Second dose date',
    booster_dose_date: 'Booster dose date',
};

export function employeeRequiredFieldLabel(fieldKey: string): string {
    return (
        EMPLOYEE_REQUIRED_FIELD_LABELS[fieldKey] ??
        fieldKey
            .replace(/_/g, ' ')
            .replace(/\b\w/g, (char) => char.toUpperCase())
    );
}

export const employeeFieldMissingHighlightClass =
    'border-rose-500/50 bg-rose-500/10 ring-1 ring-rose-500/40';

export const employeeFieldMissingLabelClass = 'text-rose-400';
